language: python
python:
  - 3.7
install:
  - pip install -q pipenv
  - pipenv install --dev
  - pipenv install codecov
script:
  - pipenv run flake8
  - pipenv run pytest pycutter --cov=pycutter
after_success:
  - pipenv run codecov
